<a href="https://colab.research.google.com/github/chum-kale/eng/blob/master/te_progsmain/DSBDA%20/asg6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score, recall_score, f1_score
%matplotlib inline

In [ ]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
x = pd.DataFrame(iris["data"], columns=iris["feature_names"])
y = pd.DataFrame(iris["target"], columns=["target"])

In [ ]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
y.head()

target
0       0
1       0
2       0
3       0
4       0

In [ ]:
scaler = StandardScaler()


In [ ]:
x = scaler.fit_transform(x.values)

In [ ]:
x_test, x_train, y_test, y_train = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model = GaussianNB()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

y_pred gets the predicted data

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[40  0  0]
 [ 0 39  2]
 [ 0  4 35]]


In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay

In [ ]:
display = ConfusionMatrixDisplay(cm)
print(display)

In [ ]:
print("Accuracy score is {0}".format(accuracy_score(y_test, y_pred)))

Accuracy score is 0.95


In [ ]:
print("Precision score is {0}".format(precision_score(y_test, y_pred, average='macro')))

Precision score is 0.9509742300439975


In [ ]:
print("Recall score is {0}".format(recall_score(y_test, y_pred, average='macro')))

Recall score is 0.9495518032103397


In [ ]:
print("F1 score is {0}".format(f1_score(y_test, y_pred, average='macro')))

F1 score is 0.9498746867167921


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.91      0.95      0.93        41
           2       0.95      0.90      0.92        39

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120

